---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model_storage_container.yaml
  - detector_models.yaml
  - orchestrator-config.yaml
  - guardrails.yaml
  - chunker.yaml
  - maas-proxy-config.yaml
  - maas-proxy.yaml
