---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    alpha.maas.opendatahub.io/tiers: '["premium", "enterprise"]'
    opendatahub.io/hardware-profile-name: unreserved-mig-71gb
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: Llama-4-Scout-17B-16E-W4A16
    serving.kserve.io/stop: "false"
  labels:
    kueue.x-k8s.io/priority-class: high-priority
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  name: llama-4-scout-17b-16e-w4a16
  namespace: prelude-maas
spec:
  model:
    name: llama-4-scout-17b-16e-w4a16
    uri: oci://registry.redhat.io/rhelai1/modelcar-llama-4-scout-17b-16e-instruct-quantized-w4a16:1.5
  replicas: 1
  router:
    gateway:
      refs:
      - name: maas-default-gateway
        namespace: openshift-ingress
    route: {}
  template:
    containers:
    - args:
      - --served-model-name={{.Name}}
      - --model=/mnt/models
      - --max-model-len=400000
      - --enable-ssl-refresh
      - --ssl-certfile=/var/run/kserve/tls/tls.crt
      - --ssl-keyfile=/var/run/kserve/tls/tls.key
      - --distributed-executor-backend=mp
      - --nnodes=1
      - --tensor-parallel-size=2
      - --pipeline-parallel-size=1
      - --trust-remote-code
      - --enable-auto-tool-choice
      - --tool-call-parser
      - llama4_pythonic
      - --chat-template
      - /opt/app-root/template/tool_chat_template_llama4_pythonic.jinja
      command:
      - python
      - -m
      - vllm.entrypoints.openai.api_server
      name: main
      resources:
        limits:
          cpu: "8"
          memory: 128Gi
          nvidia.com/mig-3g.71gb: "2"
        requests:
          cpu: "8"
          memory: 128Gi
          nvidia.com/mig-3g.71gb: "2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-4-scout-17b-16e-w4a16-sa
  namespace: prelude-maas
---
apiVersion: v1
kind: Secret
metadata:
  name: llama-4-scout-17b-16e-w4a16-sa
  namespace: prelude-maas
  annotations:
    kubernetes.io/service-account.name: "llama-4-scout-17b-16e-w4a16-sa"
    openshift.io/display-name: llama-4-scout-17b-16e-w4a16-sa
  labels:
    opendatahub.io/dashboard: "true"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: llama-4-scout-17b-16e-w4a16-view-role
  namespace: prelude-maas
rules:
- apiGroups:
  - serving.kserve.io
  resourceNames:
  - llama-4-scout-17b-16e-w4a16
  resources:
  - llminferenceservices
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: llama-4-scout-17b-16e-w4a16-view
  namespace: prelude-maas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llama-4-scout-17b-16e-w4a16-view-role
subjects:
- kind: ServiceAccount
  name: llama-4-scout-17b-16e-w4a16-sa
